[0.009s] Invoking command in '/home/stuart/lane_ws/build/custom_messages': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/stuart/lane_ws/install/lane_publisher:/opt/ros/humble /usr/bin/cmake --build /home/stuart/lane_ws/build/custom_messages -- -j16 -l16
[0.027s] -- Found ament_cmake: 1.3.5 (/opt/ros/humble/share/ament_cmake/cmake)
[0.159s] -- Found ament_lint_auto: 0.12.7 (/opt/ros/humble/share/ament_lint_auto/cmake)
[0.220s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.221s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.224s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.888s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.063s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[1.063s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[1.063s]   custom_messages --arguments-file
[1.063s]   /home/stuart/lane_ws/build/custom_messages/rosidl_adapter__arguments__custom_messages.json
[1.063s]   --output-dir
[1.063s]   /home/stuart/lane_ws/build/custom_messages/rosidl_adapter/custom_messages
[1.063s]   --output-file
[1.063s]   /home/stuart/lane_ws/build/custom_messages/rosidl_adapter/custom_messages.idls)
[1.063s]   returned error code 1:
[1.063s] 
[1.063s]   Error processing 'unit32 laneid_data' of 'custom_messages/Laneid':
[1.063s]   ''unit32' is an invalid message name.  It should have the pattern
[1.063s]   '^[A-Z][A-Za-z0-9]*$''
[1.064s] 
[1.064s]   Traceback (most recent call last):
[1.064s] 
[1.064s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[1.064s]       return _run_code(code, main_globals, None,
[1.064s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[1.064s]       exec(code, run_globals)
[1.064s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.064s]       sys.exit(main())
[1.064s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[1.064s]       abs_idl_file = convert_to_idl(
[1.064s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.064s]       return convert_msg_to_idl(
[1.064s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.064s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.064s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
[1.065s]       Type(type_string, context_package_name=pkg_name),
[1.065s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
[1.065s]       super(Type, self).__init__(
[1.065s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[1.065s]       raise InvalidResourceName(
[1.065s] 
[1.065s]   rosidl_adapter.parser.InvalidResourceName: 'unit32' is an invalid message
[1.065s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.065s] 
[1.065s] Call Stack (most recent call first):
[1.065s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.065s]   CMakeLists.txt:28 (rosidl_generate_interfaces)
[1.065s] 
[1.065s] [0m
[1.065s] -- Configuring incomplete, errors occurred!
[1.065s] See also "/home/stuart/lane_ws/build/custom_messages/CMakeFiles/CMakeOutput.log".
[1.067s] gmake: *** [Makefile:1395: cmake_check_build_system] Error 1
[1.069s] Invoked command in '/home/stuart/lane_ws/build/custom_messages' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/stuart/lane_ws/install/lane_publisher:/opt/ros/humble /usr/bin/cmake --build /home/stuart/lane_ws/build/custom_messages -- -j16 -l16
